---
- name: restart nginx
  become: true
  service: name=nginx state=restarted

- name: validate nginx configuration
  command: nginx -t -c /etc/nginx/nginx.conf
  changed_when: False

- name: reload nginx
  become: true
  service: name=nginx state=reloaded
