dist: xenial
language: python
python:
  - "2.7"
before_install:
  - "__rvm_unload ; rm -rf ~/.rvm"
install:
  - sudo apt-get update -y
  - sudo apt-get install -y openssh-server
  - pip install ansible
before_script:
  # Set up host inventory
  - echo "localhost ansible_connection=local ansible_user=root" > hosts
  # Generate dummy SSH key
  - ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
script: ansible-playbook consul.yml -i hosts --extra-vars "env=${RAILS_ENV}"
matrix:
  include:
  - env: RAILS_ENV=production
  - env: RAILS_ENV=staging
