language: python
python:
  - "3.6"
install:
  - sudo apt-get update -y
  - sudo apt-get install -y openssh-server
  - pip3 install ansible
services: mongodb
before_script:
  # Set up host inventory
  - echo "localhost ansible_connection=local ansible_user=root" > hosts
  # Generate dummy SSH key
  - ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
script: ansible-playbook consul.yml -i hosts --extra-vars "env=${RAILS_ENV} domain=localhost errbit=True"
jobs:
  include:
    - name: Xenial (production)
      dist: xenial
      env: RAILS_ENV=production
      before_install:
        - "__rvm_unload; rm -rf ~/.rvm"
    - name: Xenial (staging)
      dist: xenial
      env: RAILS_ENV=staging
      before_install:
        - "__rvm_unload; rm -rf ~/.rvm"
    - name: Bionic (production)
      dist: bionic
      env: RAILS_ENV=production
      before_install:
        - rvm get 1.28.0
        - "__rvm_unload; rm -rf ~/.rvm"
    - name: Bionic (staging)
      dist: bionic
      env: RAILS_ENV=staging
      before_install:
        - rvm get 1.28.0
        - "__rvm_unload; rm -rf ~/.rvm"
