- name: Install Tools
  become: true
  apt:
    state: latest
    update_cache: true
    name:
      - build-essential
      - cron
      - tmux
      - vim
      - htop
      - git-core
      - gpg
      - wget
      - zlib1g-dev
      - libssl-dev
      - libreadline-dev
      - libyaml-dev
      - libxml2-dev
      - libxslt1-dev
      - libffi-dev
      - curl
      - libcurl4-openssl-dev
      - libpq-dev
      - imagemagick
      - ruby-dev
      - shared-mime-info

- name: Install policykit-1
  become: true
  apt:
    state: latest
    update_cache: true
    name:
      - policykit-1
  when: ansible_distribution_release in ["bullseye"]

- name: Install polkitd and pkexec
  become: true
  apt:
    state: latest
    update_cache: true
    name:
      - polkitd
      - pkexec
  when: ansible_distribution_release not in ["bullseye"]
