- name: Use demo SMTP credentials
  replace:
    path: "{{ shared_dir }}/config/secrets.yml"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  with_items:
    - { regexp: '# mailer_delivery_method: (.)*',  line: 'mailer_delivery_method: :smtp' }
    - { regexp: '# smtp_settings:',                line: 'smtp_settings:' }
    - { regexp: '#   :address: (.)*',              line: '  :address:              "{{ smtp_address }}"' }
    - { regexp: '#   :port: (.)*',                 line: '  :port:                 {{ smtp_port }}' }
    - { regexp: '#   :domain: (.)*',               line: '  :domain:               "{{ smtp_domain }}"' }
    - { regexp: '#   :user_name: (.)*',            line: '  :user_name:            "{{ smtp_user_name }}"' }
    - { regexp: '#   :password: (.)*',             line: '  :password:             "{{ smtp_password }}"' }
    - { regexp: '#   :authentication: (.)*',       line: '  :authentication:       "{{ smtp_authentication }}"' }
    - { regexp: '#   :enable_starttls_auto: (.)*', line: '  :enable_starttls_auto: true' }
